SELECT * FROM TAB;
COMMIT;

INSERT INTO BANK
VALUES (1, 'A');
INSERT INTO BANK
VALUES (2, 'B');
SELECT * FROM BANK;

INSERT INTO PRODUCT 
VALUES(1, 1, 'PRO1', 1, 'DET1');
INSERT INTO PRODUCT 
VALUES(2, 2, 'PRO2', 2, 'DET2');
INSERT INTO PRODUCT 
VALUES(3, 1, 'PRO1', 3, 'DET1');
INSERT INTO PRODUCT 
VALUES(4, 2, 'PRO2', 4, 'DET2');
SELECT * FROM PRODUCT;

INSERT INTO "ROLE" 
VALUES (1, 'ADMIN');
INSERT INTO "ROLE" 
VALUES (2, 'MANAGER');
SELECT * FROM ROLE;
TRUNCATE TABLE ROLE;

INSERT INTO "MEMBER" 
VALUES ('ID1', 1, 'PW1', 'NAME1', 'PHONE1', 'EMAIL1');
INSERT INTO "MEMBER" 
VALUES ('ID2', 2, 'PW2', 'NAME2', 'PHONE2', 'EMAIL2');
SELECT * FROM MEMBER;

--멤버-멤버롤은 아이디 같은거, 멤버롤-롤은 롤넘버 같은거 조인
SELECT M.MEMBERNAME 
FROM "MEMBER" M
	JOIN
	--MEMBER_ROLE MR --아직 없는 테이블
	USING(MEMBERID)
	JOIN
	ROLE R
	USING(ROLENUM)
WHERE M.MEMBERID = 1;

--한명당 상품 2개씩 가입
INSERT INTO BANKBOOK 
VALUES('1234567', 'ID1', 1, 'OWNER1', sysdate);
INSERT INTO BANKBOOK 
VALUES('1234321', 'ID1', 2, 'OWNER1', sysdate);
INSERT INTO BANKBOOK 
VALUES('7654321', 'ID2', 3, 'OWNER2', sysdate);
INSERT INTO BANKBOOK 
VALUES('7654567', 'ID2', 4, 'OWNER2', sysdate);
SELECT * FROM BANKBOOK;