--TheCamp Script

SELECT * FROM TAB;
SELECT * FROM CAMPINFO;


COMMIT;
ROLLBACK;

SELECT * FROM PRODUCT_COMPONENT_VERSION;

-- session kill
SELECT a.session_id AS SESSION_ID, b.serial# AS SERIAL_NO,
a.os_user_name AS OS_USER_NAME, a.oracle_username AS ORACLE_USERNAME, b.status AS STATUS
FROM v$locked_object a, v$session b
WHERE a.session_id = b.sid;

alter system kill session '282, 60750';


SELECT * FROM CAMPINFO ORDER BY CAMPNUM ASC;


DELETE CAMPINFO WHERE CAMPNUM=26;
INSERT INTO CAMPINFO(CAMPNUM, NAME, PHONE, ADDRESS, CONTENTS)
VALUES(CAMPSEQ.NEXTVAL, 'HICAMP', '010-8463-1111', '강원 춘천시 벚꽃중앙로 275-4', '사시사철 캠핑을 즐길 수 있는 장소!');

INSERT INTO CAMPINFO
VALUES(CAMPSEQ.NEXTVAL, '밤하늘글램핑', '010-3345-1111', '강원 속초시 장성천길 153', '글램핑, 카라반, 독채, 반려동물, 바비큐장 완비');

INSERT INTO CAMPINFO
VALUES(CAMPSEQ.NEXTVAL, '동화힐링캠프', '010-9972-1111', '경기 파주시 파평면 파평산로363번길 32-9', '글램핑, 카라반, 침대방, 가족실 완비');

SELECT CAMPSEQ.NEXTVAL FROM DUAL;

UPDATE CAMPINFO SET NAME='campManiac', PHONE='010-5562-1111', ADDRESS='춘천시 경인로 778-21', CONTENTS='좋아요'
WHERE CAMPNUM=2;

SELECT COUNT(CAMPNUM) FROM CAMPINFO WHERE NAME LIKE '%바위%';


--검색, 페이징처리를 위한 쿼리문 작성, 최초 select문에 검색조건을 달아야 rownum 빈틈이 안생긴다
SELECT * FROM
(SELECT ROWNUM R, C.* FROM
(SELECT * FROM CAMPINFO
WHERE NAME LIKE '%e%'
ORDER BY CAMPNUM DESC) C)
WHERE R BETWEEN 21 AND 30;



SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)
WHERE CI.CAMPNUM=3;


SELECT * FROM CAMPFILES;



SELECT * FROM
	(SELECT ROWNUM R, C.* FROM
		(SELECT * FROM CAMPINFO CI
		LEFT OUTER JOIN
		CAMPFILES CF
		USING(CAMPNUM)
	ORDER BY CAMPNUM ASC) C)
WHERE R BETWEEN 1 AND 10;


SELECT * FROM CAMPFILES WHERE FILENUM=58;

SELECT * FROM CAMPSITE WHERE CAMPNUM=55;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPSITE CS 
	USING(CAMPNUM)
WHERE CAMPNUM=55;

SELECT * FROM CAMPINFO ORDER BY CAMPNUM DESC;
SELECT * FROM CAMPINFO ORDER BY CAMPNUM ASC;
SELECT * FROM CAMPFILES;
SELECT * FROM CAMPSITE;
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*9M', 50000, '대여가능', 'A-1');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*9M', 50000, '대여가능', 'A-2');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*11M', 80000, '대여가능', 'B-1');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '8*7M', 45000, '대여가능', 'C-1');

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, ROLENAME)
VALUES('user04', 'user04', 'seulgi', '010-0000-4444', 'user04@naver.com', 'MEMBER');

UPDATE MEMBER SET ROLENAME='ADMIN' WHERE ID='user01';
UPDATE MEMBER SET PHONE='010-0000-1111' WHERE ID='user01';
UPDATE MEMBER SET PHONE='010-0000-2222' WHERE ID='user02';
UPDATE MEMBER SET ROLENAME='CAMPMANAGER' WHERE ID='user03';
UPDATE MEMBER SET PHONE='010-0000-3333' WHERE ID='user03';

SELECT * FROM MEMBER M
	LEFT OUTER JOIN
	ADDRESS A
	USING(ID)
WHERE ID='user01';


SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CI.CAMPNUM=CS.CAMPNUM)
WHERE CI.CAMPNUM=1;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	USING(CAMPNUM)
	LEFT OUTER JOIN
	CAMPSITE CS
	USING(CAMPNUM)
WHERE CAMPNUM=1;


UPDATE CAMPINFO SET THUMBNAIL='https://www.gocamping.or.kr/upload/camp/17/thumb/thumb_720_7885JvwCp6FMBoFDXxBii374.jpg'
WHERE CAMPNUM=7;


SELECT 'EO' || ' ' || 'SOOJIN' FROM DUAL;

SELECT * FROM CAMPSITE;
INSERT INTO CAMPSITE(AREANUM, CAMPNUM, SITENAME, SITESIZE, OFFWEEKDAYSPRICE, OFFWEEKENDSPRICE, PEAKWEEKDAYSPRICE, PEAKWEEKENDSPRICE, STATUS)
VALUES(CAMPSEQ.NEXTVAL, 561, '카라반A1', '6*10', 30000, 40000, 50000, 60000, '예약가능');
INSERT INTO CAMPSITE(AREANUM, CAMPNUM, SITENAME, SITESIZE, OFFWEEKDAYSPRICE, OFFWEEKENDSPRICE, PEAKWEEKDAYSPRICE, PEAKWEEKENDSPRICE, STATUS)
VALUES(CAMPSEQ.NEXTVAL, 561, '카라반A2', '6*10', 30000, 40000, 50000, 60000, '예약가능');
INSERT INTO CAMPSITE(AREANUM, CAMPNUM, SITENAME, SITESIZE, OFFWEEKDAYSPRICE, OFFWEEKENDSPRICE, PEAKWEEKDAYSPRICE, PEAKWEEKENDSPRICE, STATUS)
VALUES(CAMPSEQ.NEXTVAL, 561, '오토A1', '10*10', 60000, 60000, 80000, 80000, '예약가능');
INSERT INTO CAMPSITE(AREANUM, CAMPNUM, SITENAME, SITESIZE, OFFWEEKDAYSPRICE, OFFWEEKENDSPRICE, PEAKWEEKDAYSPRICE, PEAKWEEKENDSPRICE, STATUS)
VALUES(CAMPSEQ.NEXTVAL, 561, '오토B1', '10*12', 90000, 90000, 110000, 110000, '예약가능');

SELECT CI.CAMPNUM, CF.FILENUM, CF.FILENAME, CS.AREANUM, CS.SITENAME FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM = CF.CAMPNUM)
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CI.CAMPNUM = CS.CAMPNUM)
WHERE CI.CAMPNUM=561
GROUP BY CI.CAMPNUM, CF.FILENUM, CF.FILENAME, CS.AREANUM, CS.SITENAME;

SELECT * FROM CAMPSITE WHERE CAMPNUM=635;

SELECT DISTINCT R, CAMPNUM, NAME, FILENUM, FILENAME FROM
	(SELECT ROWNUM R, C.* FROM
		(SELECT * FROM CAMPINFO CI
		LEFT OUTER JOIN
		CAMPFILES CF
		USING(CAMPNUM)
	ORDER BY CAMPNUM ASC) C)
WHERE R BETWEEN 1 AND 10;

--썸네일까지 조인
SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CI.CAMPNUM=CS.CAMPNUM)
	LEFT OUTER JOIN
	THUMBNAIL TH
	ON(CI.CAMPNUM=TH.CAMPNUM)
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)	
WHERE CI.CAMPNUM=734;


SELECT * FROM campinfo ORDER BY CAMPNUM DESC;
SELECT * FROM THUMBNAIL;
SELECT * FROM CAMPFILES;
SELECT * FROM CAMPSITE ORDER BY CAMPNUM ASC;
SELECT * FROM CAMPINFO WHERE CAMPNUM=560;

UPDATE THUMBNAIL SET ORINAME='0.png' WHERE CAMPNUM=758;

SELECT * FROM CAMPINFO WHERE CAMPNUM=894;
SELECT * FROM CAMPSITE WHERE CAMPNUM=904;
SELECT * FROM CAMPSITE WHERE AREANUM=905;
SELECT * FROM CAMPSITE ORDER BY AREANUM DESC;
SELECT * FROM ORDERINDEX;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM CAMPBOOK;
SELECT * FROM MEMBER;
SELECT PAYMENTSEQ.NEXTVAL FROM DUAL;
SELECT * FROM ORDERS;
SELECT * FROM STORY;
SELECT * FROM CAMPBOOK;


-- 신고 DB
SELECT * FROM BOARDTYPE;
SELECT * FROM REPORT;
DROP TABLE BOARDTYPE;
DROP TABLE REPORT;

CREATE TABLE BOARDTYPE(
	BOARDID NUMBER,
	BOARDNAME VARCHAR2(400)
)

ALTER TABLE BOARDTYPE ADD CONSTRAINT BOARDTYPE_BID_PK PRIMARY KEY (BOARDID);
ALTER TABLE QNA ADD BOARDID NUMBER;
ALTER TABLE QNACOMMENT ADD BOARDID NUMBER;
ALTER TABLE STORY ADD BOARDID NUMBER;
ALTER TABLE STORYCOMMENT ADD BOARDID NUMBER;

CREATE TABLE REPORT(
	REPORTNUM NUMBER,
	NUM NUMBER,
	BOARDID NUMBER
)

SELECT * FROM USER_CONSTRAINTS ;
ALTER TABLE REPORT DROP CONSTRAINT REPORT_NUM_QNACOMMENTFK;
ALTER TABLE REPORT ADD CONSTRAINT REPORT_NUM_QNAFK FOREIGN KEY (NUM) REFERENCES QNA(NUM) ON DELETE CASCADE;
ALTER TABLE REPORT ADD CONSTRAINT REPORT_NUM_STORYFK FOREIGN KEY (NUM) REFERENCES STORY(NUM) ON DELETE CASCADE;
ALTER TABLE REPORT ADD CONSTRAINT REPORT_NUM_QNACOMMENTFK FOREIGN KEY (NUM) REFERENCES QNACOMMENT(COMMENTNUM) ON DELETE CASCADE;
ALTER TABLE REPORT ADD CONSTRAINT REPORT_NUM_STORYCOMMENTFK FOREIGN KEY (NUM) REFERENCES STORYCOMMENT(COMMENTNUM) ON DELETE CASCADE;
ALTER TABLE BOARDTYPE DROP CONSTRAINT STORY_BID_FK;
----

-----
-- level은 1단위로 계층을 올리는 것
-- 출력 방법:없으면 한글, 'Dy' 한글로 요일, 'd' 숫자
-- d=1은 일요일 부터 1씩 늘어남.(토요일은 7)
SELECT TO_CHAR(startDate + LEVEL-1) AS dayOfWeek FROM
	(SELECT TO_DATE('2022-03-10', 'YYYY-MM-DD') AS startDate
	  		, TO_DATE('2022-03-15', 'YYYY-MM-DD') AS lastDate
	  FROM DUAL)
CONNECT BY LEVEL <= lastDate - startDate;


--쿼리
SELECT SUM(WEEK) 
 FROM (
    SELECT
      CASE WHEN dayOfWeek = '토' OR dayOfWeek = '일' THEN '10000'
          ELSE '5000'
      END AS WEEK
   FROM 
      (
         SELECT TO_CHAR(startDate + LEVEL-1, 'd') AS dayOfWeek
          FROM (
                 SELECT  TO_DATE('2023-04-10', 'YYYY-MM-DD') AS startDate
                       , TO_DATE('2023-04-13', 'YYYY-MM-DD') AS lastDate
                 FROM DUAL
              )
         CONNECT BY LEVEL <= lastDate - startDate --마지막날은 보통 계산에 넣지 않으므로, +1을 하지 않음
      ) A 
) B;
 
  
  
-----
  
SELECT * FROM MEMBER WHERE ID='user01';
SELECT * FROM CAMPBOOK;
  
SELECT * FROM CAMPBOOK WHERE AREANUM = (SELECT AREANUM FROM CAMPSITE WHERE CAMPNUM=940);
 
SELECT *
FROM CAMPBOOK CB
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CB.AREANUM=CS.AREANUM)
	LEFT OUTER JOIN
	CAMPINFO CI
	ON(CS.CAMPNUM=CI.CAMPNUM)
WHERE CI.CAMPNUM=986;

SELECT *
FROM CAMPBOOK CB
	right OUTER JOIN
	CAMPSITE CS
	ON(CB.AREANUM=CS.AREANUM)
	right OUTER JOIN
	CAMPINFO CI
	ON(CS.CAMPNUM=CI.CAMPNUM)
WHERE CI.CAMPNUM=940;

SELECT * FROM CAMPINFO WHERE CAMPNUM=940;
SELECT * FROM CAMPBOOK;

SELECT * FROM CAMPBOOK;
SELECT * FROM PAYMENT;

INSERT INTO PAYMENT(PAYNUM, ORDERNUM, PAYMETHOD, PAYDATE)
VALUES(PAYMENTSEQ.NEXTVAL, 188, '온라인 결제', SYSDATE);

SELECT * FROM PAYMENT;
DELETE PAYMENT WHERE PAYNUM=190;

SELECT * FROM CAMPBOOK WHERE ID='user01';
SELECT * FROM CAMPBOOK WHERE AREANUM=1046;

SELECT CS.*
    FROM CAMPSITE CS
    WHERE CS.CAMPNUM = #{campNum}
    AND CS.AREANUM NOT IN (
      SELECT CB.AREANUM
      FROM CAMPBOOK CB
      WHERE CB.AREANUM=CS.AREANUM
      AND (CB.STARTDATE BETWEEN #{searchStartDate} AND #{searchLastDate}
      OR CB.LASTDATE BETWEEN #{searchStartDate} AND #{searchLastDate}
      OR (CB.STARTDATE <= #{searchStartDate} AND CB.LASTDATE >= #{searchLastDate}))
    )
    
SELECT * FROM CAMPBOOK WHERE ID='user02';

PURGE RECYCLEBIN;

SELECT * FROM USER_TABLES;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM KAKAO;

SELECT * FROM CAMPINFO;
SELECT * FROM BOARDTYPE;
SELECT * FROM REPORT;

SELECT * FROM LAYOUT;
SELECT * FROM LAYOUT WHERE CAMPNUM=1;
SELECT CAMPSEQ.NEXTVAL FROM DUAL;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	LAYOUT LO 
	ON(CI.CAMPNUM=LO.CAMPNUM)
WHERE CI.CAMPNUM=1110;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CI.CAMPNUM=CS.CAMPNUM)
	LEFT OUTER JOIN
	THUMBNAIL TH
	ON(CI.CAMPNUM=TH.CAMPNUM)
	LEFT OUTER JOIN
	LAYOUT LO 
	ON(CI.CAMPNUM=LO.CAMPNUM)
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)		
WHERE CI.CAMPNUM=1110;

SELECT * FROM MEMBER;

SELECT * FROM BOARDTYPE;