--TheCamping Script

SELECT * FROM TAB;
SELECT * FROM CAMPINFO;
COMMIT;
ROLLBACK;

-- session kill
SELECT a.session_id AS SESSION_ID, b.serial# AS SERIAL_NO,
a.os_user_name AS OS_USER_NAME, a.oracle_username AS ORACLE_USERNAME, b.status AS STATUS
FROM v$locked_object a, v$session b
WHERE a.session_id = b.sid;

alter system kill session '282, 60750';


SELECT * FROM CAMPINFO ORDER BY CAMPNUM ASC;


DELETE CAMPINFO WHERE CAMPNUM=26;
INSERT INTO CAMPINFO(CAMPNUM, NAME, PHONE, ADDRESS, CONTENTS)
VALUES(CAMPSEQ.NEXTVAL, 'HICAMP', '010-8463-1111', '강원 춘천시 벚꽃중앙로 275-4', '사시사철 캠핑을 즐길 수 있는 장소!');

INSERT INTO CAMPINFO
VALUES(CAMPSEQ.NEXTVAL, '밤하늘글램핑', '010-3345-1111', '강원 속초시 장성천길 153', '글램핑, 카라반, 독채, 반려동물, 바비큐장 완비');

INSERT INTO CAMPINFO
VALUES(CAMPSEQ.NEXTVAL, '동화힐링캠프', '010-9972-1111', '경기 파주시 파평면 파평산로363번길 32-9', '글램핑, 카라반, 침대방, 가족실 완비');

SELECT CAMPSEQ.NEXTVAL FROM DUAL;

UPDATE CAMPINFO SET NAME='campManiac', PHONE='010-5562-1111', ADDRESS='춘천시 경인로 778-21', CONTENTS='좋아요'
WHERE CAMPNUM=2;

SELECT COUNT(CAMPNUM) FROM CAMPINFO WHERE NAME LIKE '%바위%';


--검색, 페이징처리를 위한 쿼리문 작성, 최초 select문에 검색조건을 달아야 rownum 빈틈이 안생긴다
SELECT * FROM
(SELECT ROWNUM R, C.* FROM
(SELECT * FROM CAMPINFO
WHERE NAME LIKE '%e%'
ORDER BY CAMPNUM DESC) C)
WHERE R BETWEEN 21 AND 30;



SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)
WHERE CI.CAMPNUM=3;


SELECT * FROM CAMPFILES;



SELECT * FROM
	(SELECT ROWNUM R, C.* FROM
		(SELECT * FROM CAMPINFO CI
		LEFT OUTER JOIN
		CAMPFILES CF
		USING(CAMPNUM)
	ORDER BY CAMPNUM ASC) C)
WHERE R BETWEEN 1 AND 10;


SELECT * FROM CAMPFILES WHERE FILENUM=58;

SELECT * FROM CAMPSITE WHERE CAMPNUM=55;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPSITE CS 
	USING(CAMPNUM)
WHERE CAMPNUM=55;

SELECT * FROM CAMPSITE;
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*9M', 50000, '대여가능', 'A-1');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*9M', 50000, '대여가능', 'A-2');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '6*11M', 80000, '대여가능', 'B-1');
INSERT INTO CAMPSITE 
VALUES(CAMPSEQ.NEXTVAL, 1, '8*7M', 45000, '대여가능', 'C-1');

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, ROLENAME)
VALUES('user04', 'user04', 'seulgi', '010-0000-4444', 'user04@naver.com', 'MEMBER');

UPDATE MEMBER SET ROLENAME='ADMIN' WHERE ID='user01';
UPDATE MEMBER SET PHONE='010-0000-1111' WHERE ID='user01';
UPDATE MEMBER SET PHONE='010-0000-2222' WHERE ID='user02';
UPDATE MEMBER SET ROLENAME='CAMPMANAGER' WHERE ID='user03';
UPDATE MEMBER SET PHONE='010-0000-3333' WHERE ID='user03';

SELECT * FROM MEMBER M
	LEFT OUTER JOIN
	ADDRESS A
	USING(ID)
WHERE ID='user01';


SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	ON(CI.CAMPNUM=CF.CAMPNUM)
	LEFT OUTER JOIN
	CAMPSITE CS
	ON(CI.CAMPNUM=CS.CAMPNUM)
WHERE CI.CAMPNUM=1;

SELECT * FROM CAMPINFO CI
	LEFT OUTER JOIN
	CAMPFILES CF
	USING(CAMPNUM)
	LEFT OUTER JOIN
	CAMPSITE CS
	USING(CAMPNUM)
WHERE CAMPNUM=1;


UPDATE CAMPINFO SET THUMBNAIL='https://www.gocamping.or.kr/upload/camp/17/thumb/thumb_720_7885JvwCp6FMBoFDXxBii374.jpg'
WHERE CAMPNUM=7;
