SELECT * FROM TAB;

COMMIT;
ROLLBACK;

DROP TABLE NOTICE;

--원래 TABLE, 이거랑 연결된거라 java코드 mapper 코드 바꿔야함(컬럼명 들어가는 부분, DTO, Mapper)
--CREATE TABLE NOTICE(
--	NOTICENUM NUMBER,
--	NOTICETITLE VARCHAR2(400),
--	NOTICEDETAIL CLOB,
--	NOTICEWRITER VARCHAR2(400),
--	NOTICEDATE DATE,
--	NOTICEHITS NUMBER
--)

CREATE TABLE NOTICE(
	NOTICENUM NUMBER,
	NOTICETITLE VARCHAR2(400),
	NOTICEDETAIL CLOB,
	NOTICEWRITER VARCHAR2(400),
	NOTICEDATE DATE,
	NOTICEHITS NUMBER
)


CREATE TABLE NOTICEFILE(
	FILENUM NUMBER,
	NOTICENUM NUMBER,
	FILENAME VARCHAR2(400),
	ORIGINALNAME VARCHAR2(400)
)


CREATE TABLE QNA(
	NUM NUMBER,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,
	WRITER VARCHAR2(200),
	REGDATE DATE,
	HIT NUMBER,
	REF NUMBER,
	STEP NUMBER,
	DEPTH NUMBER
)

CREATE TABLE QNAFILES(
	FILENUM NUMBER,
	NUM NUMBER,
	FILENAME VARCHAR2(200),
	ORINAME VARCHAR2(200)
)


CREATE SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICEFILE_SEQ;
CREATE SEQUENCE QNA_SEQ;

SELECT * FROM NOTICE ORDER BY NUM DESC;

SELECT * FROM NOTICE ORDER BY NOTICENUM DESC;
SELECT * FROM NOTICEFILE ORDER BY NOTICENUM DESC;

SELECT * FROM QNA;
SELECT * FROM QNAFILES;

SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_SEQUENCES;


ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_NNUM_PK PRIMARY KEY (NOTICENUM);

ALTER TABLE NOTICEFILE ADD CONSTRAINT NFILE_FNUM_PK PRIMARY KEY (FILENUM);

INSERT INTO NOTICE
VALUES(NOTICE_SEQ.NEXTVAL, 'NOTICE1', 'DETAIL1', 'ADMIN1', sysdate, 0);

INSERT INTO NOTICE
VALUES(NOTICE_SEQ.NEXTVAL, 'NOTICE2', 'DETAIL2', 'ADMIN1', sysdate, 0);

INSERT INTO NOTICE
VALUES(NOTICE_SEQ.NEXTVAL, 'NOTICE3', 'DETAIL3', 'ADMIN1', sysdate, 0);

INSERT INTO NOTICE(NOTICENUM, NOTICETITLE, NOTICEDETAIL, NOTICEWRITER, NOTICEDATE, NOTICEHITS)
VALUES(NOTICE_SEQ.NEXTVAL, 'NOTICE4', 'DETAIL4', 'ADMIN1', sysdate, 0);

SELECT NOTICE_SEQ.NEXTVAL FROM DUAL;
SELECT * FROM NOTICE ORDER BY NOTICENUM DESC;
SELECT * FROM NOTICE WHERE NOTICENUM = 3;

UPDATE NOTICE
SET NOTICETITLE='modititle1', NOTICEDETAIL='modidetail1', NOTICEWRITER='ADMIN2'
WHERE NOTICENUM=1;

DELETE NOTICE WHERE NOTICENUM=1;

--ROWNUM
SELECT * FROM NOTICE
ORDER BY NOTICENUM DESC;

SELECT ROWNUM R, N.* FROM
(SELECT * FROM NOTICE
ORDER BY NOTICENUM DESC) N;

SELECT * FROM
	(
	SELECT ROWNUM R, N.* FROM
		(SELECT * FROM NOTICE
		ORDER BY NOTICENUM DESC) N)
WHERE R BETWEEN 1 AND 10;

--COUNT
SELECT COUNT(NOTICENUM) FROM NOTICE;



--Script
SELECT N.*, F.*
FROM NOTICE N
	LEFT OUTER JOIN
	NOTICEFILE F
	ON(N.NOTICENUM = F.NOTICENUM)
WHERE N.NOTICENUM = 50;

INSERT INTO NOTICEFILE 
VALUES(NOTICEFILE_SEQ.NEXTVAL, 20, 'ASD', 'ASD');

INSERT INTO QNA 
VALUES(QNA_SEQ.NEXTVAL, 'title6', 'contents6', 'winter', sysdate, 0, 0, 0, 0);