SELECT * FROM tab;
SELECT * FROM MEMBER;
SELECT * FROM USER_CONSTRAINTS;
COMMIT;

--DROP TABLE MEMBER;


--TABLE
CREATE TABLE MEMBER(
	ID VARCHAR2(200),-- CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(200),
	NAME VARCHAR2(200),
	ADDRESS VARCHAR2(200),
	PHONENUM VARCHAR2(200),
	EMAIL VARCHAR2(200)
);


CREATE TABLE OPENING_ACCOUNT(
	ACCOUNTNUM VARCHAR2(200),
	PRODUCTNUM NUMBER,
	ID VARCHAR2(200),
	HIREDATE DATE,
	NAME VARCHAR2(200),
	BALANCE NUMBER,
	ACCOUNTPW NUMBER
);


CREATE TABLE BANK_PRODUCT(
	PRODUCTNUM NUMBER,
	INTEREST NUMBER(2,1),
	PRODUCTNAME VARCHAR2(200),
	PRODUCTOPTION VARCHAR2(200),
	PRODUCTLIST VARCHAR2(200)
);


CREATE TABLE CARD(
	CARDNUM NUMBER,
	PRODUCTNUM NUMBER,
	ACCOUNTNUM VARCHAR2(200),
	ID VARCHAR2(200),
	CVC NUMBER(3),
	AMOUNT NUMBER,
	LIMIT NUMBER
);


CREATE TABLE INQUIRY(
	INQUIRYNUM NUMBER,
	ACCOUNTNUM VARCHAR2(200),
	DWDATE DATE,
	BALANCE NUMBER,
	REMITTANCEACC VARCHAR2(200),
	RECEIVEDACC VARCHAR2(200),
	SENDERNAME VARCHAR2(200)
);


CREATE TABLE LOAN(
	LOANNUM VARCHAR2(200),
	ACCOUNTNUM VARCHAR2(200),
	ID VARCHAR2(200),
	PRODUCTNUM NUMBER,
	INTEREST NUMBER(2,1),
	LOANMONEY NUMBER
);


CREATE TABLE SHARES(
	SHARENUM VARCHAR2(200),
	ACCOUNTNUM VARCHAR2(200),
	ID VARCHAR2(200),
	PRODUCTNUM NUMBER,
	SHAREMONEY NUMBER,
	CASHHELD NUMBER
);


--CONSTRAINT
--MEMBER TABLE
ALTER TABLE MEMBER ADD CONSTRAINT ID_PK PRIMARY KEY (ID);

--OPENING_ACCOUNT
ALTER TABLE OPENING_ACCOUNT ADD CONSTRAINT ACC_NUM_PK PRIMARY KEY (ACCOUNTNUM);
ALTER TABLE OPENING_ACCOUNT ADD CONSTRAINT PRODUCTNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES BANK_PRODUCT (PRODUCTNUM);
ALTER TABLE OPENING_ACCOUNT ADD CONSTRAINT PRODUCTID_FK FOREIGN KEY (ID) REFERENCES MEMBER;

--BANK_PRODUCT
ALTER TABLE BANK_PRODUCT ADD CONSTRAINT PRODUCTNUM_PK PRIMARY KEY (PRODUCTNUM);

--CARD
ALTER TABLE CARD ADD CONSTRAINT CARD_PK PRIMARY KEY (CARDNUM);
ALTER TABLE CARD ADD CONSTRAINT CARDPRO_FK FOREIGN KEY (PRODUCTNUM) REFERENCES BANK_PRODUCT;
ALTER TABLE CARD ADD CONSTRAINT CARDACC_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES OPENING_ACCOUNT (ACCOUNTNUM);
ALTER TABLE CARD ADD CONSTRAINT CARDID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID); --에러(MEMBER로 수정)

--INQUIRY
ALTER TABLE INQUIRY ADD CONSTRAINT INQUIRY_PK PRIMARY KEY (INQUIRYNUM);
ALTER TABLE INQUIRY ADD CONSTRAINT INACC_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES OPENING_ACCOUNT (ACCOUNTNUM);

--LOAN
ALTER TABLE LOAN ADD CONSTRAINT LOANNUM_PK PRIMARY KEY (LOANNUM);
ALTER TABLE LOAN ADD CONSTRAINT LOANACC_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES OPENING_ACCOUNT (ACCOUNTNUM);
ALTER TABLE LOAN ADD CONSTRAINT LOANID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID); --에러
ALTER TABLE LOAN ADD CONSTRAINT LOANPRO_FK FOREIGN KEY (PRODUCTNUM) REFERENCES BANK_PRODUCT (PRODUCTNUM);

--SHARES
ALTER TABLE SHARES ADD CONSTRAINT SHARENUM_PK PRIMARY KEY (SHARENUM);
ALTER TABLE SHARES ADD CONSTRAINT SHAREACC_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES OPENING_ACCOUNT (ACCOUNTNUM);
ALTER TABLE SHARES ADD CONSTRAINT SHAREID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID); --에러
ALTER TABLE SHARES ADD CONSTRAINT SHAREPRO_FK FOREIGN KEY (PRODUCTNUM) REFERENCES BANK_PRODUCT (PRODUCTNUM);

--SEQUENCE
--없음