SELECT * FROM TAB;

CREATE TABLE BANK(
   BANKNUM NUMBER,
   BANKNAME VARCHAR2(200) CONSTRAINT BANK_BNAME_U UNIQUE NOT NULL
);


   
ALTER TABLE BANK ADD CONSTRAINT BANK_NUM_PK PRIMARY KEY(BANKNUM);


SELECT * FROM BANK;

SELECT * FROM PRODUCT;


PURGE RECYCLEBIN;




CREATE TABLE PRODUCT(
   PRODUCTNUM NUMBER,
   BANKNUM NUMBER,
   PRODUCTNAME VARCHAR2(200) NOT NULL,
   INTEREST NUMBER(3,1) CONSTRAINT PRODUCT_INT_CHECK CHECK  (INTEREST >0),
   PRODUCTDETAIL CLOB 
)

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PNUM_PK PRIMARY KEY(PRODUCTNUM);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_BNUM_FK FOREIGN KEY(BANKNUM) REFERENCES BANK;




CREATE TABLE MEMBER(
   MEMBERID VARCHAR2(200) ,
   BANKNUM NUMBER,
   MEMBERPW VARCHAR2(200) NOT NULL,
   MEMBERNAME VARCHAR2(200) NOT NULL,
   MEMBERPHONE VARCHAR2(200) CONSTRAINT MEMBER_MPHONE_U UNIQUE NOT NULL,
   MEMBEREMAL VARCHAR2(200) CONSTRAINT MEMBER_MEMAIL_U UNIQUE
);


ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_MID_PK PRIMARY KEY(MEMBERID);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBERBANK_NUM_FK FOREIGN KEY(BANKNUM) REFERENCES BANK;


SELECT * FROM MEMBER;




CREATE TABLE BANKBOOK (
   BOOKNUM VARCHAR2(200),
   MEMBERID VARCHAR2(200),
   PRODUCTNUM NUMBER,
   BOOKOWNER VARCHAR2(200) NOT NULL,
   BOOKDATE DATE NOT NULL
)

SELECT * FROM BANKBOOK

ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_BNUM_PK PRIMARY KEY(BOOKNUM);
ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_MID_FK FOREIGN KEY(MEMBERID) REFERENCES MEMBER;
ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_PNUM_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT;


CREATE TABLE DEAL(
   DEALDATE DATE,
   BOOKNUM VARCHAR2(200),
   MONEYFLOW NUMBER NOT NULL,
   BALANCE NUMBER NOT NULL
)

SELECT * FROM DEAL;

DROP TABLE DEAL;
DROP TABLE BANKBOOK;
DROP TABLE PRODUCT;
DROP TABLE ROLE;
SELECT * FROM TAB;

CREATE TABLE BANK(
   BANKNUM NUMBER,
   BANKNAME VARCHAR2(200) CONSTRAINT BANK_BNAME_U UNIQUE NOT NULL
);


   
ALTER TABLE BANK ADD CONSTRAINT BANK_NUM_PK PRIMARY KEY(BANKNUM);


SELECT * FROM BANK;

SELECT * FROM PRODUCT;


PURGE RECYCLEBIN;




CREATE TABLE PRODUCT(
   PRODUCTNUM NUMBER,
   BANKNUM NUMBER,
   PRODUCTNAME VARCHAR2(200) NOT NULL,
   INTEREST NUMBER(3,1) CONSTRAINT PRODUCT_INT_CHECK CHECK  (INTEREST >0),
   PRODUCTDETAIL CLOB 
)

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PNUM_PK PRIMARY KEY(PRODUCTNUM);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_BNUM_FK FOREIGN KEY(BANKNUM) REFERENCES BANK;





CREATE TABLE MEMBER(
   MEMBERID VARCHAR2(200) ,
   BANKNUM NUMBER,
   MEMBERPW VARCHAR2(200) NOT NULL,
   MEMBERNAME VARCHAR2(200) NOT NULL,
   MEMBERPHONE VARCHAR2(200) CONSTRAINT MEMBER_MPHONE_U UNIQUE NOT NULL,
   MEMBEREMAL VARCHAR2(200) CONSTRAINT MEMBER_MEMAIL_U UNIQUE
);


ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_MID_PK PRIMARY KEY(MEMBERID);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_BNUM_FK FOREIGN KEY(BANKNUM) REFERENCES BANK;
ALTER TABLE MEMBER DROP CONSTRAINT MEMBERBANK_NUM_FK;


SELECT * FROM MEMBER;




CREATE TABLE BANKBOOK (
   BOOKNUM VARCHAR2(200),
   MEMBERID VARCHAR2(200),
   PRODUCTNUM NUMBER,
   BOOKOWNER VARCHAR2(200) NOT NULL,
   BOOKDATE DATE NOT NULL
)

SELECT * FROM BANKBOOK

ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_BNUM_PK PRIMARY KEY(BOOKNUM);
ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_MID_FK FOREIGN KEY(MEMBERID) REFERENCES MEMBER;
ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_PNUM_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT;


CREATE TABLE DEAL(
   DEALDATE DATE,
   BOOKNUM VARCHAR2(200),
   MONEYFLOW NUMBER NOT NULL,
   BALANCE NUMBER NOT NULL
)

SELECT * FROM DEAL;

DROP TABLE DEAL;
DROP TABLE BANKBOOK;
DROP TABLE PRODUCT;
DROP TABLE "MEMBER";
DROP TABLE BANK;
DROP TABLE MEMBER_ROLE


ALTER TABLE DEAL ADD CONSTRAINT DEAL_DDATE_PK PRIMARY KEY(DEALDATE);
ALTER TABLE DEAL ADD CONSTRAINT DEAL_BNUM_FK FOREIGN KEY(BOOKNUM) REFERENCES BANKBOOK;
ALTER TABLE DEAL DROP CONSTRAINT DEAL_BOOKNUM_FK;


SELECT * FROM USER_CONSTRAINTS;

DROP TABLE ROLE


CREATE SEQUENCE BANKNUM_SEQ;
CREATE SEQUENCE PRODUCTNUM_SEQ;
DROP TABLE BANK;


ALTER TABLE DEAL ADD CONSTRAINT DEAL_DDATE_PK PRIMARY KEY(DEALDATE);
ALTER TABLE DEAL ADD CONSTRAINT DEAL_BOOKNUM_FK FOREIGN KEY(BOOKNUM) REFERENCES BANKBOOK;


SELECT * FROM USER_CONSTRAINTS;


CREATE TABLE ROLE (
   ROLENUM NUMBER CONSTRAINT ROLE_RNUM_PK PRIMARY KEY,
   ROLENAME VARCHAR2(200)
)

CREATE TABLE MEMEBER_ROLE(
   MEMBERID  VARCHAR2(200) CONSTRAINT MROLE_MID_FK REFERENCES MEMBER,
   ROLENUM NUMBER CONSTRAINT MROLE_RNUM_FK REFERENCES ROLE
)

CREATE SEQUENCE BANKNUM_SEQ
CREATE SEQUENCE PRODUCTNUM_SEQ

SELECT * FROM BANK;
SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM BANKBOOK;
SELECT * FROM DEAL;
SELECT * FROM ROLE;
SELECT * FROM MEMEBER_ROLE;

COMMIT;

ALTER TABLE MEMEBER_ROLE RENAME TO MEMBER_ROLE;
SELECT * FROM USER_CONSTRAINTS;


------------------------------------------------------------------------------------

