SELECT * FROM TRADE TAB;

COMMIT;
ROLLBACK;

CREATE TABLE NOTICE(
	NOTICENUM NUMBER,
	NOTICETITLE VARCHAR2(400),
	NOTICEDETAIL CLOB,
	NOTICENAME VARCHAR2(400),
	NOTICEDATE DATE,
	NOTICEHITS NUMBER
)

CREATE SEQUENCE NOTICE_SEQ;


SELECT * FROM NOTICE;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_SEQUENCES ;


ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_NNUM_PK PRIMARY KEY (NOTICENUM);