--강사님꺼 erd보고 만든 BANKBOOK table
SELECT * FROM TAB;
SELECT * FROM BANKBOOK;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM USER_CONSTRAINTS;

CREATE TABLE BANKBOOK(
	BOOKNUMBER NUMBER,
	BOOKNAME VARCHAR2(100),
	BOOKRATE NUMBER(3,2),
	BOOKSALE NUMBER(1),
	BOOKDETAIL CLOB
)

CREATE SEQUENCE BANKBOOK_SEQ;

ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_BNUM_PK PRIMARY KEY (BOOKNUMBER);