--강사님꺼 erd보고 만든 BANKBOOK table
SELECT * FROM TAB;
SELECT * FROM BANKBOOK;

CREATE TABLE BANKBOOK(
	BOOKNUMBER NUMBER,
	BOOKNAME VARCHAR2(100),
	BOOKRATE NUMBER(3,2),
	BOOKSALE NUMBER(1),
	BOOKDETAIL CLOB
)

ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_BNUM_PK PRIMARY KEY;