SELECT * FROM TAB;

PURGE RECYCLEBIN;
COMMIT;
ROLLBACK;

SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_SEQUENCES;

SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTOPTION;
SELECT * FROM COMMENTARY;
SELECT * FROM MEMBER;
SELECT * FROM ADDRESS;
SELECT * FROM ROLE;
SELECT * FROM MEMBER_ROLE;


SELECT PRODUCTNUM_SEQ.NEXTVAL FROM DUAL;