SELECT * FROM TAB;

PURGE RECYCLEBIN;
COMMIT;
ROLLBACK;

SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTOPTION;
SELECT * FROM COMMENTARY;
SELECT * FROM MEMBER;
SELECT * FROM ADDRESS;
SELECT * FROM ROLE;
SELECT * FROM MEMBER_ROLE;