--서브쿼리 실습문제

--1. 사번이 198번인 사원이 근무하는 부서가 있는 도시가 속해있는 나라가 있는 대륙 정보?
SELECT * FROM REGIONS r ;
SELECT * FROM COUNTRIES c ;
SELECT * FROM LOCATIONS l ;
SELECT * FROM DEPARTMENTS d ;
SELECT * FROM EMPLOYEES e ;

SELECT REGION_NAME  
FROM REGIONS r 
WHERE REGION_ID =(
	SELECT REGION_ID 
	FROM COUNTRIES c
	WHERE COUNTRY_ID =(
		SELECT COUNTRY_ID 
		FROM LOCATIONS l
		WHERE LOCATION_ID = (
			SELECT LOCATION_ID 
			FROM DEPARTMENTS d 
			WHERE DEPARTMENT_ID =(
				SELECT DEPARTMENT_ID 
				FROM EMPLOYEES e 
				WHERE EMPLOYEE_ID = '198'
			)
		)
	)	
);


--2. LAST_NAME이 Khoo인 사람이 근무하는 부서명
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS d 
WHERE DEPARTMENT_ID =(
	SELECT DEPARTMENT_ID 
	FROM EMPLOYEES e 
	WHERE LAST_NAME = 'Khoo'
);


--3. 사원번호가 199번인 사원의 매니저가 근무하는 부서가 있는 나라명
SELECT COUNTRY_NAME 
FROM COUNTRIES c 
WHERE COUNTRY_ID =(
	SELECT COUNTRY_ID 
	FROM LOCATIONS l 
	WHERE LOCATION_ID =(
		SELECT LOCATION_ID 
		FROM DEPARTMENTS d 
		WHERE DEPARTMENT_ID =(
		SELECT DEPARTMENT_ID 
		FROM EMPLOYEES e 
		WHERE EMPLOYEE_ID = '199'
		)
	)
);


--4. 사원들 중에서 월급이 가장 적은 사원이 근무하는 도시명
SELECT CITY 
FROM LOCATIONS l 
WHERE LOCATION_ID =(
	SELECT LOCATION_ID 
	FROM DEPARTMENTS d 
	WHERE DEPARTMENT_ID =(
		SELECT DEPARTMENT_ID 
		FROM EMPLOYEES e
		WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES e)
	)
);


--5. 부서명이 IT인 부서에 근무하는 사원들의 모든 정보
SELECT *
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID =(
	SELECT DEPARTMENT_ID 
	FROM DEPARTMENTS d 
	WHERE DEPARTMENT_NAME LIKE 'IT'
);


--6. Employees 테이블에서 LAST_NAME이 Greenberg인 사원보다 급여를 더 많이 받고있는 사원들의 모든 정보
SELECT *
FROM EMPLOYEES e 
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES e WHERE LAST_NAME ='Greenberg');


--7. 부서별 최소급여를 받고 있는 사원의 정보 출력
--부서별 사람 출력
--부서별로 모인 사람들을 그룹화 하고
--HAVING으로 그룹마다 조건을 주면 될려나?
--얘는 아직 안배운거라 강사님 실습 정답 보고 생각해보자.
SELECT *
FROM EMPLOYEES e 
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY);

(SELECT MIN(SALARY) FROM EMPLOYEES e2);


--8.
