SELECT * FROM TAB;

PURGE RECYCLEBIN;

COMMIT;

--1. 부서명이 IT인 부서에 근무하는 사원들의 모든 정보 출력 (20점)
SELECT * FROM EMPLOYEES e ;

SELECT * FROM DEPARTMENTS d ;

SELECT * FROM EMPLOYEES E
	INNER JOIN
	DEPARTMENTS D 
	ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE D.DEPARTMENT_NAME = 'IT';



--2. Employees 테이블에서 LAST_NAME이 Greenberg 사원보다 급여를 더 많이 받고 있는 사원들정보 출력 (20점)
SELECT * FROM EMPLOYEES e ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES E
WHERE SALARY > (
	SELECT SALARY FROM EMPLOYEES E2
	WHERE LAST_NAME = 'Greenberg'
	)
ORDER BY SALARY DESC;


--3. 부서별 최소급여를 받고 있는 사원의 정보 출력 (20점)
SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS d ;

SELECT MIN(SALARY) FROM EMPLOYEES E
WHERE DEPARTMENT_ID = 10;

SELECT * FROM EMPLOYEES WHERE 
    (JOB_ID, SALARY) IN
    (SELECT JOB_ID, MIN(SALARY) FROM EMPLOYEES e GROUP BY JOB_ID);
ORDER BY JOB_ID;

SELECT * FROM EMPLOYEES WHERE 
	(DEPARTMENT_ID, SALARY) IN
	(SELECT DEPARTMENT_ID, MIN(SALARY) FROM EMPLOYEES e2 GROUP BY DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;


SELECT *
FROM EMPLOYEES e 
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES e2 GROUP BY DEPARTMENT_ID);


--4. 도시이름이 'S'로시작하는 지역에 근무하는 사원의 정보 출력 (20점)
SELECT * FROM LOCATIONS l ;
SELECT * FROM DEPARTMENTS d ;
SELECT * FROM EMPLOYEES e ;

SELECT * FROM LOCATIONS l
WHERE CITY LIKE 'S%';

SELECT * FROM EMPLOYEES E
	LEFT OUTER JOIN
	DEPARTMENTS D
	ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
	LEFT OUTER JOIN 
	LOCATIONS L 
	ON(D.LOCATION_ID=L.LOCATION_ID)
WHERE L.CITY LIKE 'S%';


--5. 성이 Austin 사원의 매니저(상사)가 근무하는 부서의 평균 급여보다 부서평균이 더 큰 부서의 이름 (20점)
--Austin 사원의 매니저는 103번
--manager_id가 103인 부서는 60번
--60번 부서의 평균 급여 구하기 = 5760
SELECT * FROM EMPLOYEES e2 ;


--60번 부서의 평균 급여
SELECT AVG(SALARY) FROM EMPLOYEES e 
WHERE DEPARTMENT_ID =(
	SELECT DISTINCT DEPARTMENT_ID  FROM EMPLOYEES e
	WHERE MANAGER_ID = (
		SELECT MANAGER_ID  FROM EMPLOYEES e 
		WHERE LAST_NAME = 'Austin'
		)
	);


--각 부서의 급여 평균
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES e 
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)
ORDER BY AVG(SALARY) DESC;


--60번 부서의 평균 급여보다 각 부서의 급여평균이 더 큰 것만 찾아내기 위한 쿼리???
SELECT DEPARTMENT_NAME  FROM DEPARTMENTS d WHERE DEPARTMENT_ID IN 
	(
	SELECT DEPARTMENT_ID FROM EMPLOYEES e 
	GROUP BY DEPARTMENT_ID
	HAVING AVG(SALARY) > (
		SELECT AVG(SALARY) FROM EMPLOYEES e 
		WHERE DEPARTMENT_ID =(
			SELECT DISTINCT DEPARTMENT_ID  FROM EMPLOYEES e
			WHERE MANAGER_ID = (
				SELECT MANAGER_ID  FROM EMPLOYEES e 
				WHERE LAST_NAME = 'Austin'
				)
			)
		)
	);
