SELECT * FROM TAB;

PURGE RECYCLEBIN;

ROLLBACK;
COMMIT;

--TABLE 생성
CREATE TABLE PRODUCT(
	PRODUCTNUM NUMBER,
	PRODUCTNAME VARCHAR2(200),
	PRODUCTDETAIL CLOB,
	PRODUCTSCORE NUMBER(2,1)
)

CREATE TABLE PRODUCTOPTION(
	OPTIONNUM NUMBER,
	PRODUCTNUM NUMBER,
	OPTIONNAME VARCHAR2(200),
	OPTIONPRICE NUMBER,
	OPTIONSTOCK NUMBER
)

CREATE TABLE COMMENTARY(
	COMMENTNUM NUMBER,
	PRODUCTNUM NUMBER,
	ID VARCHAR2(200),
	COMMENTSCORE NUMBER(2,1),
	COMMENTDATE DATE,
	COMMENTARY VARCHAR2(500)
)

CREATE TABLE MEMBER(
	ID VARCHAR2(200),
	PW VARCHAR2(200),
	MEMBERNAME VARCHAR2(200),
	MEMBERPHONE VARCHAR2(200),
	EMAIL VARCHAR2(200)
)

CREATE TABLE ADDRESS(
	ADDRESSNUM NUMBER,
	ID VARCHAR2(200),
	ADDRESS VARCHAR2(200),
	ADDRESSPHONE VARCHAR2(200),
	ADDRESSNAME VARCHAR2(200)
)

CREATE TABLE ROLE(
	ROLENUM NUMBER,
	ROLENAME VARCHAR2(200)
)

CREATE TABLE MEMBER_ROLE(
	ID VARCHAR2(200),
	ROLENUM NUMBER
)

--TABLE SELECT
SELECT * FROM TAB;
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTOPTION;
SELECT * FROM COMMENTARY;
SELECT * FROM MEMBER;
SELECT * FROM ADDRESS;
SELECT * FROM ROLE;
SELECT * FROM MEMBER_ROLE;


--CONSTRAINTS
SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PNUM_PK PRIMARY KEY (PRODUCTNUM);

ALTER TABLE PRODUCTOPTION ADD CONSTRAINT POPTION_OPNUM_PK PRIMARY KEY (OPTIONNUM);
ALTER TABLE PRODUCTOPTION ADD CONSTRAINT POPTION_PNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE; 

ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_CNUM_PK PRIMARY KEY (COMMENTNUM);
ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_PNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE;
ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_ID_KF FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_ANUM_PK PRIMARY KEY (ADDRESSNUM);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_IN_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;

ALTER TABLE ROLE ADD CONSTRAINT ROLE_RNUM_PK PRIMARY KEY (ROLENUM);

ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MROLE_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;
ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MROLE_RNUM_FK FOREIGN KEY (ROLENUM) REFERENCES ROLE (ROLENUM) ON DELETE CASCADE;


--TABLE에 필요한 시퀀스 만들기
CREATE SEQUENCE PRODUCTNUM_SEQ;
CREATE SEQUENCE OPTIONNUM_SEQ;
CREATE SEQUENCE COMMENTNUM_SEQ;

INSERT INTO PRODUCT 
VALUES(PRODUCTNUM_SEQ.NEXTVAL, '텀블러', '상세설명1', 5);
INSERT INTO PRODUCT 
VALUES(PRODUCTNUM_SEQ.NEXTVAL, '빨대', '상세설명2', 3);
INSERT INTO PRODUCT 
VALUES(PRODUCTNUM_SEQ.NEXTVAL, '컵받침대', '상세설명3', 1);

INSERT INTO PRODUCTOPTION
VALUES(OPTIONNUM_SEQ.NEXTVAL, ?, '옵션A', 50000, 10);


--
SELECT * FROM PRODUCT WHERE PRODUCTNUM = 1;