--table 만들기
--owner

CREATE TABLE PRODUCT (
	PRODUCTNUM NUMBER CONSTRAINT PRODUCT_NUM_PK PRIMARY KEY,
	PRODUCTNAME VARCHAR2(50),
	PRODUCTDETAIL CLOB,
	PRODUCTSCORE NUMBER(2, 1)
);


CREATE TABLE PRODUCTOPTION (
	OPTIONNUM NUMBER CONSTRAINT PRODUCTOPTION_NUM_PK PRIMARY KEY,
	PRODUCTNAME VARCHAR2(50),
	PRODUCTPRICE NUMBER,
	PRODUCTSTOCK NUMBER,
	PRODUCTNUM NUMBER
);


CREATE TABLE COMMENTARY(
	COMMENTNUM NUMBER CONSTRAINT COMMENT_NUM_PK PRIMARY KEY,
	COMMENTSCORE NUMBER(2, 1),
	COMMENTDATE DATE,
	COMMENTARY VARCHAR2(500),
	PRODUCTNUM NUMBER,
	ID VARCHAR2(50)
);

SELECT * FROM USER_CONSTRAINTS;
ROLLBACK;
COMMIT;

--PRODUCT 작업
SELECT * FROM PRODUCT;


--PRODUCTOPTION 작업
SELECT * FROM PRODUCTOPTION;
ALTER TABLE "PRODUCTOPTION" ADD CONSTRAINT POPTION_OPNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE;

ALTER TABLE "PRODUCTOPTION" DROP CONSTRAINT POPTION_OPNUM_FK;

--COMMENTARY 작업
SELECT * FROM COMMENTARY;
ALTER TABLE "COMMENTARY" ADD CONSTRAINT COMMENTARY_PNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE;
ALTER TABLE "COMMENTARY" ADD CONSTRAINT COMMENTARY_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;

ALTER TABLE "COMMENTARY" DROP CONSTRAINT COMMENTARY_PNUM_FK;
ALTER TABLE "COMMENTARY" DROP CONSTRAINT COMMENTARY_ID_FK;

--TEST용
CREATE SEQUENCE COMMENTARY_SEQ;
INSERT INTO PRODUCT 
VALUES (PRODUCT_SEQ.NEXTVAL, '123', '12345', 5.5);
SELECT * FROM PRODUCT p ;

TRUNCATE TABLE PRODUCT;
SELECT * FROM RECYCLEBIN;