
--230125 7교시
--회원가입
--이름, ID, PW, 전화번호, 이메일, 나이

CREATE TABLE MEMBER(
	ID VARCHAR2(50),
	PW VARCHAR2(50),
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50),
	EMAIL VARCHAR2(100),
	AGE NUMBER(3)
);

SELECT * FROM MEMBER;
DROP TABLE MEMBER;

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, AGE)
VALUES('test', 'test1', 'test', '010-1111-2222', 'test@gmail.com', 30);

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, AGE)
VALUES('test', 'test', 'test', NULL, NULL, 20);

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, AGE)
VALUES('test2', 'test', 'test', '0101111', NULL, 20);

--결함이 있는 데이터를 못들어오게 막아주는것 : 제약조건
SELECT * FROM USER_CONSTRAINTS ;

CREATE TABLE MEMBER(
	ID VARCHAR2(50) PRIMARY KEY,
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) UNIQUE,
	EMAIL VARCHAR2(100),
	AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 120)
);
--위와 같이 주면 제약조건에 위배 됐을때 문제점을 발견하기가 힘들다. (이렇게 쓰지 마세요)


-- 1. column 레벨 방식
CREATE TABLE MEMBER(
	ID VARCHAR2(50) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(50) CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) CONSTRAINT MEMBER_PHONE_U UNIQUE,
	EMAIL VARCHAR2(100) CONSTRAINT MEMBER_EMAIL_U UNIQUE,
	AGE NUMBER(3) CHECK (AGE > 0 AND AGE < 120)
);


-- 2. table 레벨 방식
CREATE TABLE MEMBER(
	ID VARCHAR2(50),
	PW VARCHAR2(50) CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50),
	EMAIL VARCHAR2(100),
	AGE NUMBER(3) CHECK (AGE > 0 AND AGE < 120),
	CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID),
	CONSTRAINT MEMBER_PHONE_U UNIQUE (PHONE),
	CONSTRAINT MEMBER_EMAIL_U UNIQUE (EMAIL)
);


-- 게시판을 만들려고 함. 컬럼레벨방식으로
CREATE TABLE BOARD(
	NUM NUMBER CONSTRAINT BOARD_NUM_PK PRIMARY KEY,
	TITLE VARCHAR2(200),
	CONTENTS CLOB, --최대 4GB까지 담을 수 있어서 데이터 제한을 줄 필요가 없음
	WRITER VARCHAR2(50) CONSTRAINT BOARD_W_FK REFERENCES MEMBER(ID),
	REGDATE DATE,
	HIT NUMBER
);
--BOARD의 WRITER가 MEMBER의 ID를 참조해야한다.(ID 없이 글을 쓸 수 없기 때문에)
--MEMBER가 항상 글을 쓸 필요는 없지만, 쓰여진 글은 MEMBER가 꼭 필요하다(이게 Foregin Key)
SELECT * FROM BOARD;
DROP TABLE BOARD;

INSERT INTO MEMBER(ID, PW, NAME, PHONE, EMAIL, AGE)
VALUES('W1', 'test1', 'test', '010-1111-2222', 'test@gmail.com', 30);

INSERT INTO BOARD 
VALUES(1, 'T1', 'C1', 'W1', sysdate, 0);

DELETE MEMBER WHERE ID = 'W1';
DELETE BOARD WHERE NUM = 1;