CREATE USER user01 IDENTIFIED BY user01
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE, DBA TO user01;

COMMIT;


CREATE USER USER02 IDENTIFIED BY USER02
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE, DBA TO USER02;

COMMIT;