SELECT * FROM tab;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	ID VARCHAR2(200),-- CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(200),
	NAME VARCHAR2(200),
	ADDRESS VARCHAR2(200),
	PHONENUM VARCHAR2(200),
	EMAIL VARCHAR2(200)
);

SELECT * FROM USER_CONSTRAINTS;

DROP TABLE MEMBER CASCADE;