--Table 생성

--이름, 전화번호, 이메일, 나이가 들어갈 Table 생성, test로 insert 2개정도

CREATE TABLE ROULETTE(
	NAME VARCHAR2(100),
	PHONE_NUMBER VARCHAR(13),
	EMAIL VARCHAR2(20),
	AGE NUMBER(3)
);

SELECT * FROM ROULETTE;
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

INSERT INTO ROULETTE 
VALUES ('ASDF', 010-0000-0000, 'QWER', 50);

ROLLBACK;
DROP TABLE ROULETTE;