SELECT * FROM TAB;

PURGE RECYCLEBIN;

COMMIT;
ROLLBACK;


----------------------------------------------------------------------------------
--TABLE 생성, 조회, 삭제(문제 있을 때 바로)
CREATE TABLE PRODUCT(
	PRODUCTNUM NUMBER,
	PRODUCTNAME VARCHAR2(200),
	PRODUCTDETAIL CLOB,
	PRODUCTSCORE NUMBER(2,1)
)

CREATE TABLE PRODUCTOPTION(
	OPTIONNUM NUMBER,
	PRODUCTNUM NUMBER,
	OPTIONNAME VARCHAR2(200),
	OPTIONPRICE NUMBER,
	OPTIONSTOCK NUMBER
)

CREATE TABLE COMMENTARY(
	COMMENTNUM NUMBER,
	PRODUCTNUM NUMBER,
	ID VARCHAR2(200),
	COMMENTSCORE NUMBER(2,1),
	COMMENTDATE DATE,
	COMMENTARY VARCHAR2(500)
)

CREATE TABLE MEMBER(
	ID VARCHAR2(200),
	PW VARCHAR2(200),
	MEMBERNAME VARCHAR2(200),
	MEMBERPHONE VARCHAR2(200),
	EMAIL VARCHAR2(200)
)

/*CREATE TABLE ADDRESS(
	ADDRESSNUM NUMBER,
	ID VARCHAR2(200),
	ADDRESS VARCHAR2(200),
	ADDRESSPHONE VARCHAR2(200),
	ADDRESSNAME VARCHAR2(200)
)*/

CREATE TABLE ROLE(
	ROLENUM NUMBER,
	ROLENAME VARCHAR2(200)
)

CREATE TABLE MEMBER_ROLE(
	ID VARCHAR2(200),
	ROLENUM NUMBER
)

CREATE TABLE BANKBOOK(
	BOOKNUMBER NUMBER,
	BOOKNAME VARCHAR2(200),
	BOOKRATE NUMBER(2,1),
	BOOKSALE NUMBER,
	BOOKDETAIL VARCHAR2(200)
)

CREATE TABLE ACCOUNT(
	ACCOUNTNUM NUMBER,
	ID VARCHAR2(200),
	BOOKNUMBER NUMBER,
	ACCOUNTDATE DATE,
	ACCOUNTBALANCE NUMBER
)

CREATE TABLE TRADE(
	TRADENUM NUMBER,
	ACCOUNTNUM NUMBER,
	TRADEBALANCE NUMBER,
	TRADETABLE DATE,
	TRADEIO NUMBER,
	TRADEAMOUNT VARCHAR2(200)
)

CREATE TABLE BANKBOOKIMG(
	FILENUM NUMBER,
	BOOKNUMBER NUMBER,
	FILENAME VARCHAR2(400),
	ORINAME VARCHAR2(400)
)

--230222 JavaScript와 연계 연습
CREATE TABLE BANKBOOKCOMMENT(
	NUM NUMBER,
	BOOKNUMBER NUMBER,
	CONTENTS VARCHAR2(4000),
	REGDATE DATE,
	WRITER VARCHAR2(200)
)

CREATE TABLE NOTICE(
	NUM NUMBER,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,
	WRITER VARCHAR2(200),
	REGDATE DATE,
	HIT NUMBER
)

CREATE TABLE NOTICEFILES(
	FILENUM NUMBER,
	NUM NUMBER,
	FILENAME VARCHAR2(200),
	ORINAME VARCHAR2(200)
)

CREATE TABLE QNA(
	NUM NUMBER,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,
	WRITER VARCHAR2(200),
	REGDATE DATE,
	HIT NUMBER,
	REF NUMBER,
	STEP NUMBER,
	DEPTH NUMBER
)

CREATE TABLE QNAFILES(
	FILENUM NUMBER,
	NUM NUMBER,
	FILENAME VARCHAR2(200),
	ORINAME VARCHAR2(200)
)

--원래 TABLE, 이거랑 연결된거라 java코드 mapper 코드 바꿔야함(컬럼명 들어가는 부분, DTO, Mapper)
--CREATE TABLE NOTICE(
--	NOTICENUM NUMBER,
--	NOTICETITLE VARCHAR2(400),
--	NOTICEDETAIL CLOB,
--	NOTICEWRITER VARCHAR2(400),
--	NOTICEDATE DATE,
--	NOTICEHITS NUMBER
--)


----------------------------------------------------------------------------------
--TABLE 조회, 삭제, 데이터 지우기
SELECT * FROM PRODUCT ORDER BY PRODUCTNUM DESC;
SELECT * FROM PRODUCTOPTION ORDER BY OPTIONNUM DESC;
SELECT * FROM COMMENTARY;

SELECT * FROM MEMBER;
--SELECT * FROM ADDRESS;
SELECT * FROM ROLE;
SELECT * FROM MEMBER_ROLE;

SELECT * FROM BANKBOOK;
SELECT * FROM ACCOUNT ORDER BY DESC;
SELECT * FROM TRADE ORDER BY TRADENUM DESC;
SELECT * FROM BANKBOOKIMG ORDER BY FILENUM DESC;
SELECT * FROM BANKBOOKCOMMENT ORDER BY NUM DESC;

SELECT * FROM NOTICE ORDER BY NUM DESC;
SELECT * FROM NOTICEFILES ORDER BY FILENUM DESC;
SELECT * FROM QNA ORDER BY NUM DESC;
SELECT * FROM QNAFILES ORDER BY FILENUM DESC;


DROP TABLE PRODUCT;
DROP TABLE PRODUCTOPTION;
DROP TABLE COMMENTARY;

DROP TABLE MEMBER;
--DROP TABLE ADDRESS;
DROP TABLE ROLE;
DROP TABLE MEMBER_ROLE;

DROP TABLE BANKBOOK;
DROP TABLE ACCOUNT;
DROP TABLE TRADE;
DROP TABLE BANKBOOKIMG;
DROP TABLE BANKBOOKCOMMENT;

DROP TABLE NOTICE;
DROP TABLE NOTICEFILES;
DROP TABLE QNA;
DROP TABLE QNAFILES;


TRUNCATE TABLE ACCOUNT;


----------------------------------------------------------------------------------
--SEQUENCE 생성, 조회, 삭제
SELECT * FROM USER_SEQUENCES;
CREATE SEQUENCE PRODUCTNUM_SEQ;
CREATE SEQUENCE OPTIONNUM_SEQ;
CREATE SEQUENCE COMMENTNUM_SEQ;

CREATE SEQUENCE ROLE_SEQ;

CREATE SEQUENCE BANKNUM_SEQ;
CREATE SEQUENCE ACCOUNTNUM_SEQ;
CREATE SEQUENCE TRADENUM_SEQ;

CREATE SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICEFILES_SEQ;
CREATE SEQUENCE QNA_SEQ;
CREATE SEQUENCE QNAFILES_SEQ;
--BANKBOOKCOMMENT SEQ 나중에 만들려고 했는데 NOTICE, QNA랑 같이 쓴다함


DROP SEQUENCE NOTICEFIELS_SEQ;



----------------------------------------------------------------------------------
--CONSTRAINT 생성 및 전체조회
SELECT * FROM USER_CONSTRAINTS;

--PK CONSTRAINT
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PNUM_PK PRIMARY KEY (PRODUCTNUM);
ALTER TABLE PRODUCTOPTION ADD CONSTRAINT POPTION_OPNUM_PK PRIMARY KEY (OPTIONNUM);
ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_CNUM_PK PRIMARY KEY (COMMENTNUM);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID);
--ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_ANUM_PK PRIMARY KEY (ADDRESSNUM);
ALTER TABLE ROLE ADD CONSTRAINT ROLE_RNUM_PK PRIMARY KEY (ROLENUM);

ALTER TABLE BANKBOOK ADD CONSTRAINT BANKBOOK_BNUM_PK PRIMARY KEY (BOOKNUMBER);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ANUM_PK PRIMARY KEY (ACCOUNTNUM);
ALTER TABLE TRADE ADD CONSTRAINT TRADE_TNUM_PK PRIMARY KEY (TRADENUM);
ALTER TABLE BANKBOOKIMG ADD CONSTRAINT BBIMG_FNUM_PK PRIMARY KEY (FILENUM);
ALTER TABLE BANKBOOKCOMMENT ADD CONSTRAINT BBCOMMENT_NUM_PK PRIMARY KEY (NUM);

ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_NUM_PK PRIMARY KEY (NUM);
ALTER TABLE NOTICEFILES ADD CONSTRAINT NFILES_FNUM_PK PRIMARY KEY (FILENUM);
ALTER TABLE QNA ADD CONSTRAINT QNA_NUM_PK PRIMARY KEY (NUM);
ALTER TABLE QNAFILES ADD CONSTRAINT QFILES_FNUM_PK PRIMARY KEY (FILENUM);


--FK CONSTRAINT
ALTER TABLE PRODUCTOPTION ADD CONSTRAINT POPTION_PNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE; 
ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_PNUM_FK FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE;
ALTER TABLE COMMENTARY ADD CONSTRAINT COMMENTARY_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;

--ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_IN_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;
ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MROLE_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;
ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MROLE_RNUM_FK FOREIGN KEY (ROLENUM) REFERENCES ROLE (ROLENUM) ON DELETE CASCADE;

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_BNUM_FK FOREIGN KEY (BOOKNUMBER) REFERENCES BANKBOOK (BOOKNUMBER) ON DELETE CASCADE;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;
ALTER TABLE TRADE ADD CONSTRAINT TRADE_ANUM_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES ACCOUNT (ACCOUNTNUM) ON DELETE CASCADE;
ALTER TABLE BANKBOOKIMG ADD CONSTRAINT BBIMG_BNUM_FK FOREIGN KEY (BOOKNUMBER) REFERENCES BANKBOOK (BOOKNUMBER) ON DELETE CASCADE;
ALTER TABLE BANKBOOKCOMMENT ADD CONSTRAINT BBCOMMENT_FNUM_FK FOREIGN KEY (BOOKNUMBER) REFERENCES BANKBOOK (BOOKNUMBER) ON DELETE CASCADE;

ALTER TABLE NOTICEFILES ADD CONSTRAINT NFILES_NUM_FK FOREIGN KEY (NUM) REFERENCES NOTICE (NUM) ON DELETE CASCADE;
ALTER TABLE QNAFILES ADD CONSTRAINT QFILES_NUM_FK FOREIGN KEY (NUM) REFERENCES QNA (NUM) ON DELETE CASCADE;


--DROP CONSTRAINT
ALTER TABLE NOTICEFILES DROP CONSTRAINT NFILES_FNUM_PK;
ALTER TABLE BANKBOOKIMG DROP CONSTRAINT BBIMG_BNUM_FK;
ALTER TABLE BANKBOOKCOMMENT DROP CONSTRAINT BBCOMMENT_FNUM_FK;


